# test default config
# config load sequence: _default.yaml -> user assigned *.yaml -> command line args

rtl:
  base-url: https://raw.githubusercontent.com/XS-MLVP/UnityChipXiangShanRTLs/refs/heads/main/README.md
  version: latest
  cache-dir: "../rtl"

test:
  skip-tags: ["LONG_TIME_RUN"]
  run-tags: []
  skip-cases: []
  run-cases: []
  skip-exceptions: []

output:
  out-dir: "../out"

report:
  report-dir: "report"
  report-name: "%{host}-%{pid}-%{time}/index.html"
  information:
    title: "XiangShan KMH Test Report"
    user:
      name: "User"
      emial: "User@example.email.com"
    line_grate: 90
    meta:
      Version: "1.0"

log:
  root-level: "debug"
  term-level: "info"
  file-dir: "log"
  file-name: "%{host}-%{pid}-%{time}.log"
  file-level: "info"
