# test default config
# config load sequence: default.yaml -> ENV args -> user assigned *.yaml -> command line args

rtl:
  base-url: https://raw.githubusercontent.com/XS-MLVP/UnityChipXiangShanRTLs/refs/heads/main/README.md
  version: latest
  cache-dir: "../rtl"

test:
  skip-tags: ["LONG_TIME_RUN"]
  run-tags: []
  skip-cases: []
  run-cases: []
  skip-exceptions: []

output:
  out-dir: "../out"
  report-dir: "report"
  log-dir: "log"

log:
  level: "info"
  log-file: "log-%{node}-%{thread}-%{time}.txt"
