# test default config
# config load sequence: default.yaml -> ENV args -> user assigned *.yaml -> command line args

rtl:
  base-url: https://raw.githubusercontent.com/XS-MLVP/UnityChipXiangShanRTLs/refs/heads/main/README.md
  version: latest
  cache-dir: "../rtl"

test:
  test-model: "full"
  ignore: []

output:
  out-dir: "../out"
  report-dir: "report"

log:
  level: "Debug"
